#!/usr/bin/env bash

sudo apt update
sudo apt install git stow curl xinput -y
stow --adopt -t $HOME -d $HOME/dotfiles -S fish git i3 i3status

sudo add-apt-repository ppa:fish-shell/release-4 -y
sudo apt update
sudo apt install fish -y
chsh -s /usr/bin/fish

curl https://mise.run | sh
~/.local/bin/mise use -g fzf rg jq lazygit node go jujutsu clang make

sudo apt install i3 -y

install_deb() {
    local url="$1"
    local file
    file="$(mktemp --suffix=.deb)"
    curl -fL "$url" -o "$file"
    sudo apt install -y "$file"
    rm -f "$file"
}

install_deb "$(curl -fsSL https://api.github.com/repos/VSCodium/vscodium/releases/latest \
    | jq -r '.assets[] | select(.name|test("amd64\\.deb$")) | .browser_download_url' \
    | head -1)"

install_deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

install_deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

sudo apt install lightdm -y

curl -fsSL https://tailscale.com/install.sh | sh